### ISSUE TITLE
The synthesized audio sounds like it through the voice changer.

### ISSUE THREAD

**Issue by YihWenWang** [Tomiinek/Multilingual_Text_to_Speech#10]
[audio.zip](https://github.com/Tomiinek/Multilingual_Text_to_Speech/files/5005247/audio.zip)
I used the two kinds of language datasets including VCTK(English, 30 speakers, 11654 clips) and STCMDS(Chinese, 30 speakers, 3600 clips).
This result is good when I synthesized the Chinese text.
But when I used the three kinds of language datasets including VCTK, STCMDS, and TAT(Minnan Language, 30 speakers, 8586 clips), the result is bad.
When I synthesized the Chinese text, the synthesized audio sounds like it through the voice changer, and the speaking is too fast.
There are synthesized waveforms such as two languages and three languages in the compressed file.
I don't have any idea about this problem.

**Comment by Tomiinek** [comment]
Hello, glad to hear that your two-language model is working :+1: 

Again, it is hard to tell what is happening there. I haven't encountered this problem and have no idea what could be the cause.
I would guess that your training recordings are not normalized properly.

**Comment by YihWenWang** [comment]
Do you mean "ffmpeg normalization" ?
Could it be because of the "speaker_embedding_dimension": 32 ?

**Comment by Tomiinek** [comment]
> Could it be because of the "speaker_embedding_dimension": 32 ?

I do not think so. The model just cannot speed up output recordings. I do not know what is it caused by, but it seems like you are feeding there faster training examples for a part of your dataset.

**Comment by michael-conrad** [comment]
A shot in the dark. You might try changing the phonemizer call to include stress marks in it's output and create new training metadata from scratch with the revised phonemes and see if that helps.

**Comment by YihWenWang** [comment]
Thank you very much.
I have solved this problem when I use the same sample rate 22050 kHz in each language dataset.

**Comment by nltoan** [comment]
can you share your config for 2 dataset? @YihWenWang 
my mail is: bubeo@icloud.com

**Comment by padmanabhankrishnamurthy** [comment]
> Thank you very much.
> I have solved this problem when I use the same sample rate 22050 kHz in each language dataset.

Hi,

Would you mind sharing what library you used for resampling the datasets?

Thanks!
