### ISSUE TITLE
Is there a way to specify phonemes, stress, and vowel lengths for the inputs?

### ISSUE THREAD

**Issue by michael-conrad** [Tomiinek/Multilingual_Text_to_Speech#11]
Providing pre-phonetized content?

Is there a way to specify phonemes, stress, and vowel lengths for the inputs and skip the phonemizer step?

I'm looking for a way to synthesize two different Native American languages: Cherokee and Mohegan.

### Mohegan

The Mohegan language is a stress based language, and I'm hoping the phonetics would map close enough to one or more of the languages already trained for the creation of language lesson materials.

### Cherokee

The Cherokee language is a tone based language and this factor presents a challenge.

I'm wondering if it might be possible to "bootstrap" a language such as Cherokee using espeak-ng generated training audio and phonetics then use voice cloning for the actual output. (And skip training the vocoder on the espeak-ng audio).

**Comment by Tomiinek** [comment]
Hello, pretty cool languages! :+1: 

You can currently specify just phonemes. Stress, tones, or vowel lengths are not supported. It is not needed to use `phonemizer`, you can use whatever charset and phonemicized variants you want. Just set `use_phonemes` and `phonemes` parameters and create your training meta-file with the following format:

```
id|speaker|language|audio_file_path|mel_spectrogram_path|linear_spectrogram_path|text|phonemicized_text
```

I think that adding a possibility to input stresses or tones would be definitely helpful. But using these features would require training data with labeled stresses and tones and it might be hard-to-get :disappointed: 

> I'm wondering if it might be possible to "bootstrap" a language such as Cherokee using espeak-ng generated training audio and phonetics then use voice cloning for the actual output. (And skip training the vocoder on the espeak-ng audio).

I think this is not possible. Do I understand it correctly that you would use audios synthesized with `espeak-ng` for training the model? And that your goal is to make the synthesis in those languages more natural? `espeak-ng` produces robotic sounds. To clone a voice across languages, the model needs to learn (and disentangle) what are the aspects related to language and voice (that is why we want more speakers per language). The model would probably think that the robotic sound is also an attribute of the Mohegan or Cherokee language. 

But I think that a pretty low amount of natural multi-speaker (like 3 speakers) data (e.g., ~1 hour) for both languages could be enough for training. You can record your own dataset :smile: (and train the model jointly on phoneme inputs in more languages). But I guess that this is the thing you are trying to avoid, isn't it?

**Comment by michael-conrad** [comment]
On Sun, Aug 2, 2020, 11:55 AM Tomáš Nekvinda <notifications@github.com>
wrote:

> Hello, pretty cool languages! 👍
>

Thanks!

You can currently specify just phonemes. Stress, tones, or vowel lengths
> are not supported.
>

I know the phonemizer uses espeak to do some of the work and espeaks
phonetics include stress marks.

> It is not needed to use phonemizer, you can use whatever charset and
> phonemicized variants you want. Just set use_phonemes and phonemes
> parameters and create your training meta-file with the following format:
>
> id|speaker|language|audio_file_path|mel_spectrogram_path|linear_spectrogram_path|text|phonemicized_text
>
>
> I think that adding a possibility to input stresses or tones would be
> definitely helpful. But using these features would require training data
> with labeled stresses and tones and it might be hard-to-get 😞
>
> I'm wondering if it might be possible to "bootstrap" a language such as
> Cherokee using espeak-ng generated training audio and phonetics then use
> voice cloning for the actual output. (And skip training the vocoder on the
> espeak-ng audio).
>
> I think this is not possible. Do I understand it correctly that you would
> use audios synthesized with espeak-ng for training the model? And that
> your goal is to make the synthesis in those languages more natural?
>
For Cherokee

Using the voice cloning approach I'm hoping would reduce the robot sound
some. If it reduces it enough and the needed pitch contours remain intact,
I was thinking it should be possible to treat the output as intermediate,
then retrain again with the intermediate as new audio.

For Mohegan I'm hoping I can just abuse the existing phonetics to produce
close enough output for practical use in learning materials. I already have
code to abuse Amazon Polly neural in such a fashion, but there isn't a
neural language with all the required phonemes in a single set.

espeak-ng produces robotic sounds. To clone a voice across languages, the
model needs to learn (and disentangle) what are the aspects related to
language and voice (that is why we want more speakers per language). The
model would probably think that the robotic sound is also an attribute of
the Mohegan or Cherokee language.

> But I think that a pretty low amount of natural multi-speaker (like 3
> speakers) data (e.g., ~1 hour) for both languages could be enough for
> training. You can record your own dataset 😄 (and train the model jointly
> on phoneme inputs in more languages). But I guess that this is the thing
> you are trying to avoid, isn't it?
>

It's really a matter of available trying data.

**Comment by Tomiinek** [comment]
> Using the voice cloning approach I'm hoping would reduce the robot soundsome. If it reduces it enough and the needed pitch contours remain intact, I was thinking it should be possible to treat the output as intermediate, then retrain again with the intermediate as new audio.

Oh, I see, it would be interesting to try it out :+1: 

> For Mohegan I'm hoping I can just abuse the existing phonetics to produce close enough output for practical use in learning materials.

It should work if you can abuse the phonetics. I have seen [a paper](https://arxiv.org/abs/1904.06508) which might be useful for you:

> Yuan-Jui Chen, Tao Tu, Cheng chieh Yeh, and Hung-Yi Lee. End-to-End Text-To-Speech for Low-Resource Languages by Cross-Lingual Transfer Learning. In Proc. Interspeech 2019, pages 2075–2079, 2019.

**Comment by michael-conrad** [comment]
> I think that adding a possibility to input stresses or tones would be definitely helpful. But using these features would require training data with labeled stresses and tones and it might be hard-to-get disappointed

I applied a patch here to have phonemizer output stress marks. (At least I think  it is - Is the phonemizer's output cached anywhere?)

```diff
diff --git a/utils/text.py b/utils/text.py
index e5f7a2a..b33ee6c 100644
--- a/utils/text.py
+++ b/utils/text.py
@@ -88,7 +88,7 @@ def to_phoneme(text, ignore_punctuation, language, phoneme_dictionary=None):
 def _phonemize(text, language):
     try:
         seperators = Separator(word=' ', phone='')
-        phonemes = phonemize(text, separator=seperators, backend='espeak', language=language)           
+        phonemes = phonemize(text, separator=seperators, backend='espeak', with_stress=True, language=language)           
     except RuntimeError:
         epi = epitran.Epitran(language)
         phonemes = epi.transliterate(text, normpunc=True)
```
