### ISSUE TITLE
Question: Adding speakers to existing languages.

### ISSUE THREAD

**Issue by michael-conrad** [Tomiinek/Multilingual_Text_to_Speech#20]
Is it possible to stop training then add additional speakers to train.txt and val.txt then resume training?

Will the added speakers show up as additional entries in the model param dict or will it halt with an error?

**Comment by bcoghe** [comment]
I am interested in this as well. I have 4 hours of one dutch-speaking speaker. Is it possible to fine-tune your pretrained model by just generating a new train.txt file and by starting training from a checkpoint? Where can I find the pre-trained checkpoint (as i only find the .pyt files)

**Comment by michael-conrad** [comment]
From what I understand:

a) The pretrained model is only useful for inference.

b) The fine tuning routines are not part of the current code - I tried recreating them, but failed.

c) Without the fine tuning routines, you can't change speakers and languages.
