### ISSUE TITLE
How to add other language?

### ISSUE THREAD

**Issue by bubeo** [Tomiinek/Multilingual_Text_to_Speech#21]
Thank you for sharing
I want to ask about initialization for 2 languages. Vietnam and English (using LJSpeech)
Can you let me ask about the places to configure?
Because your code is a bit confusing.

**Comment by Tomiinek** [comment]
Hello! Please have a look at the issue #7 first. Is it helpful?

**Comment by bubeo** [comment]
> Hello! Please have a look at the issue #7 first. Is it helpful?

Thank you, but i think it is not helpful for me:(.
Can you show me what is the work I need to do to configure the 2 languages? (file, dataset,...)

**Comment by Tigl** [comment]
Hi,
I have a dataset of 5 speakers. But for some reasons they have the same transcript. Do you think it would be a problem to train them at the same time?
Not a big problem right? Because I think we separate sentences to words finally. The only problem is valuation  (valuate the trained sentences)?
