### ISSUE TITLE
I want add support for Urdu

### ISSUE THREAD

**Issue by paklau99988** [Tomiinek/Multilingual_Text_to_Speech#22]
Hello,
It is very great repo! thanks. 
Need make training for Urdu (arabic letters). How can make dataset like yours? Need change vocabulary somewhere?

**Comment by Tomiinek** [comment]
Hi! :slightly_smiling_face: 

At first, please read through the issue #7, it may be helpful for you.

To build your dataset: If you have any audio-transcript pairs in Urdu, just mix them with the dataset provided in this repository and make sure that it has similar transcripts length distribution and audio duration distribution. You can use this jupyter notebook `notebooks/analyze.ipynb` for the analysis. 

You do not need to change vocabulary as the model is character-based. So you do have to extend it with the list of Arabic letters. Specifically, change the parameter `characters` to something like ``abcdefghijklmnopqrstuvwxyzçèéßäöōǎǐíǒàáǔüèéìūòóùúāēěīâêôûñőűабвгдежзийклмнопрстуфхцчшщъыьэюяёوهنملكقفغعظطضصشسزرذدخحجثتبيا`` (I do not undrestand the Arabic script, but it should be a simple text string with every possible character in the alphabet, also make sure that encoding and everything works)  

Best wishes, Tomas

**Comment by paklau99988** [comment]
Thanks you very much! 
I run the code analyze.py, get error:

```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-449f082df24f> in <module>
      3 metafile = "all_reduced.txt"
      4 dataset_root = "../data/css10"
----> 5 data = TextToSpeechDataset(os.path.join(dataset_root, metafile), dataset_root)

~/Multilingual_Text_to_Speech/dataset/dataset.py in __init__(self, meta_file, dataset_root_dir, known_unique_speakers)
     82         unique_speakers_set = set(self.unique_speakers)
     83         self.items = []
---> 84         with open(meta_file, 'r', encoding='utf-8') as f:
     85             for line in f:
     86                 line_tokens = line[:-1].split('|')

FileNotFoundError: [Errno 2] No such file or directory: '../data/css10/all_reduced.txt'
```
How create file /all_reduced.txt? is not in folder.

**Comment by Tomiinek** [comment]
Use a dataset meta-file that exists, for example `metafile = "all.txt"`. The notebook is intended just for quick experiments and plotting of some data. You do not have to run it completly or as is.
