### ISSUE TITLE
How can I expand a language like Korean?

### ISSUE THREAD

**Issue by sooftware** [Tomiinek/Multilingual_Text_to_Speech#25]
Hi Tomminek!  
Thank You for your great Paper & Source Code.  
  
I want to expand a language like Korean.  
Also, I want to apply voice cloning in the Korean Language.  
  
For voice cloning, I think the Korean dataset should be made of multi-speakers... Did I get it right??  
If so, then can you tell some parts I can refer to??  It would be very helpful.  
  
Thank You.

**Comment by Tomiinek** [comment]
Ah, I missed this issue, sorry for a late response.
 
At first, please read through the issue #7 
Is it helpful for you?

Yes, you definitely need more speakers for a reliable voice cloning.

**Comment by sooftware** [comment]
Thanks a lot Tomiinek!!
