### ISSUE TITLE
I have a question about the paper.

### ISSUE THREAD

**Issue by sooftware** [Tomiinek/Multilingual_Text_to_Speech#26]
Hi Tommiinek!  
I have a question about the paper.  
  
![image](https://user-images.githubusercontent.com/42150335/96847564-4c1fdc00-148e-11eb-9c66-d99f6905b85c.png)
  
Above figure, I think it's multi-language input.   
Then can you explain how the lanugage ID is embedded?  
  
Thank You!

**Comment by Tomiinek** [comment]
Hello :slightly_smiling_face: 

The figure tries to show a training batch with two examples, one is in Latin and the other in Chinese. So the model is given also a vector of two language IDs (like [0,1]) which are converted into an embedding with a higher dimension.

During inference, when a single code-switched input such as "Hello 王" is pushed into the model, it is converted into a batch of the same two textual inputs and with different languages, i.e. [0,1]. The two outputs of the encoder are then mixed together, as we know from the input which characters are from which language and then this mixed vector of encoder outputs are passed into the decoder.

**Comment by Tomiinek** [comment]
I hope I remember it correctly :smile:

**Comment by sooftware** [comment]
You mean, Language ID 0 generate parameter to Conv group 1, Language ID 1 generate parameter to Conv group 2 right??

**Comment by Tomiinek** [comment]
Exactly :slightly_smiling_face:

**Comment by sooftware** [comment]
Thank You Tomminek!!
