### ISSUE TITLE
Discuss Chinese-English mixed TTS.

### ISSUE THREAD

**Issue by leijue222** [Tomiinek/Multilingual_Text_to_Speech#27]
Hi, @Tomiinek . It's a nice job, and it's an honor to see this project.
I have some questions about train.txt; hope you can solve my puzzle.

1. How to get the original train.txt file?
Git clone this project, under `/data/css10/`, we can see the **train.txt (original)**.
After the `prepare_css_spectrograms.py` file is processed, we got the spectrogram and linear spectrogram and changed the structure of **train.txt (processed)**

> ```python
> (original) 000285|chinese|chinese|chinese/call_to_arms/call_to_arms_0285.wav|||húixiāngdòu de húizì， zěnyáng xiě de?|
> (processed) 000285|chinese|chinese|chinese/call_to_arms/call_to_arms_0285.wav|spectrograms\000285.npy|linear_spectrograms\000285.npy|húixiāngdòu de húizì， zěnyáng xiě de?|
> ```

So, how to get the train.txt (original) file? I want to create it for another dataset.

2. The structure of train.txt

I have questions about the meaning of these variables: `idx`, `s`, `ph`
https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/ca00959d231bcfe0dc845d8c1938e869daf3feae/data/prepare_css_spectrograms.py#L57

1. `idx`:  As long as we make sure that IDX is unique and points to specific audio, we can define it in any way we want, right? Usually, the id is defined by the name of the file, but I found that you did not do this. Can I define this variable with the filename of the audio?

2. `s`:  speaker? Puzzle. If the data set has only one person's voice, it is defined as the language name? Otherwise, it is defined as the serial number of different people (0,1,2,3,4....)?

3. `ph`:  I don't understand the meaning of this variable, is that mean "\n"?

**Comment by Tomiinek** [comment]
Hello, thank you!

1. At first, you have to write your own loader that will go through transcripts and audio files of your custom dataset. It is enough to implement it in the file [`loaders.py`](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/master/dataset/loaders.py), I have already implemented some loaders for popular datasets such as LJSpeech, VCTK and M-AILABS. So you can start with the code and modify it to your own dataset. Second, you will have to run the script [TextToSpeechDataset.create_meta_file](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/7d96891d22e586660c6da654f7af702749eafc68/dataset/dataset.py#L193). Please, read through its description and adjust the arguments to your needs. It will generate the meta-file and spectrograms you are looking for :slightly_smiling_face: Note that the `dataset_name` argument should match the name of your loder function, i.e., for example for generating the meta-file of M-AILABS use `dataset_name = mailabs`.

2. The meta-file format is also described in the function mentioned above. `idx` - yes, exactly as you say; `s` - it is just a speaker id, so you can use whatever you want, I used languge name and possibly a suffix if there were more speakers of the particular language (e.g., `zh-00`, `zh-01`, ...); `ph` - this field can contain a phonemicized variant of the transcript, again, it can be automatically generated with the function above (but it takes really long time).

Enjoy! :partying_face:

**Comment by leijue222** [comment]
Thank you for your detailed reply.
Your code specification and looks comfortable. I noticed the `loaders.py` file, and then I tried to use the `ljspeech` function to load the dataset and added the `biaobei` function to load the dataset in the reference format.
So I processed two datasets now:

1. LJSpeech: 13,100 English audio clips | 24 hours | one woman speaker
2. [Biaobei](https://test.data-baker.com/#/data/index/source): 10,000 Chinese audio clips | 12 hours | one woman speaker

**Question 1**: The parameter "generator_bottleneck_dim" and "generator_dim" set be what number will be ok?
**Question 2**: Maybe I don't have to run the script `TextToSpeechDataset.create_meta_file`?
I had seen the description. It used to create spectrograms, linear spectrograms, and phonemized_text.
As I said yesterday, we already got the spectrogram and linear spectrogram after the prepare_css_spectrograms.py and changed the structure of train.txt to add `spectrogram | linear spectrogram`.  The `phonemized_text` in the `prepare_css_spectrograms.py` is `ph`, because the `ph=""`, so I asked you what it means.
I can keep the `ph=""` right? I just use Chinese and English dataset. And in your example, I see the `ph=""` too.
![Snipaste_2020-10-31_11-04-44](https://user-images.githubusercontent.com/30276789/97769807-f8398500-1b68-11eb-892d-05cdb9ac30b7.png)

**Comment by Tomiinek** [comment]
Congratulations :slightly_smiling_face: 

1. You use just two languages, so I would choose very low numbers such as `generator_bottleneck_dim=1` and `generator_dim=2`. Note that the performance gain is more visible if you use more language for training, even if you do not use them later during inference. Also, you need more speakers in the data for a successful voice cloning and code-switching (see this issue #7)

2. You are absolutely right. If you already merged the datasets and run `prepare_css_spectrograms.py`, you do not need to run `TextToSpeechDataset.create_meta_file` anymore. Yes, just keep `ph=""`, it means there is no phonemicized variant, so it cannot be used later via the parameter `use_phonemes = True`.

**Comment by leijue222** [comment]
> Congratulations 🙂
> 
> 1. You use just two languages, so I would choose very low numbers such as `generator_bottleneck_dim=1` and `generator_dim=2`. Note that the performance gain is more visible if you use more language for training, even if you do not use them later during inference. Also, you need more speakers in the data for a successful voice cloning and code-switching (see this issue #7)
> 2. You are absolutely right. If you already merged the datasets and run `prepare_css_spectrograms.py`, you do not need to run `TextToSpeechDataset.create_meta_file` anymore. Yes, just keep `ph=""`, it means there is no phonemicized variant, so it cannot be used later via the parameter `use_phonemes = True`.

Thanks!

1. I want to start by using these two datasets to get through the whole pipeline. Then, I'll try to tune it by adding more speakers of these two languages.
2. I got it! Choose one of `prepare_css_spectrograms.py`and `TextToSpeechDataset.create_meta_file` to get spectrogram and linear spectrogram is fine. And Chinese and English do not need the phonemicized variant, so just keep `ph=""`.
Thanks again for your reply, best regards to you.

**Comment by leijue222** [comment]
There is an error when I run train.py: `AttributeError: type object 'Params' has no attribute 'mel_normalize_mean'`
The error comes from:
https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/utils/audio.py#L105
Then I checked the `params.py`, found that there is indeed no definition of the `mel_normalize_mean `and `lin_normalize_mean`.
How can I solve this error? @Tomiinek

**Comment by leijue222** [comment]
OK, I see! 
https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/train.py#L248 
The `mel_normalize_mean ` parameter was successfully calculated on line 248, but `audio.py` didn't get it, let me figure out how to solve it.

**Comment by leijue222** [comment]
Environment: The system is win10, and other environments are consistent with requirement.txt
I made the following changes to make it able to run train.py:

1. Write the parameter result of this [line ](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/train.py#L248)into param.py.

2. change this line
https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/modules/encoder.py#L41
to:
```
x = torch.nn.utils.rnn.pack_padded_sequence(x, x_lenghts, batch_first=True, enforce_sorted=False)
```
Otherwise, it will get the following error:
```
RuntimeError: `lengths` array must be sorted in decreasing order when `enforce_sorted` is True. You can pass `enforce_sorted=False` to pack_padded_sequence and/or pack_sequence to sidestep this requ
irement if you do not need ONNX exportability.
```

Finally, I can run train.py with a warning of: `UserWarning: PyTorch is not compiled with NCCL support
  warnings.warn('PyTorch is not compiled with NCCL support')`

It might have been running for an hour, the logs are here:
![logs](https://user-images.githubusercontent.com/30276789/97796487-9272f900-1c4d-11eb-8f28-458d604b58a1.png)

@Tomiinek 
Therefore, I have some question:
The result of the two parameters is a two-dimensional array with 80 rows. Is it the correct way to write them directly into param.py?
And is there anything wrong with my above operation?

**Comment by Tomiinek** [comment]
Hello,

- Ad the parameters you should change) I think that you are using a single speaker per language, so you can probably set `multi_speaker = False`.

- Ad `params.py`) I do not know how is it possible. These two parameters are calculated once you start training from scratch (and not from a checkpoint). They are clearly assigned before any further usage :confused:  It does input spectrogram normalization, i.e. it goes through your dataset, computes mean and variance for each of the 80 rows. These values are afterwards saved so that they can be later used: https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/train.py#L246-L250 It is needed to save them into `Params` because they have to be used again during inference or when restoring a checkpoint.

- Ad `warning: audio amplitude out of range, auto clipped.`) This can happen at the beginning of training, because output spectrograms can be strange and their inversion produces invalid audios.

**Comment by Tomiinek** [comment]
Logs look ok ... the total loss and MCD is falling down, great news! :slightly_smiling_face:

**Comment by leijue222** [comment]
The Loss trend is good, so it seems that adding the `enforce_sorted=False` parameter in `encorde.py` should not have much effect.

Maybe I have to stop now and set `multi_speaker=False` to training from scratch?
By the way, how long will it have good results, or say how many steps should be trained, 50K?

I don’t know if the way I save these two parameters is correct？
My current way is to manually add `mel_normalize_mean` and `mel_normalize_variance` to params.py:
![parpams](https://user-images.githubusercontent.com/30276789/97800259-c6124b00-1c6e-11eb-8b50-bf736a2be5ec.png)
Is this the right way to add parameters manually? I feel a bit silly my way.
Because `train.py` calculated their values, but audio.py can't get the values, then I will get an error of `type object 'Params' has no attribute 'mel_normalize_mean'`. So I have to do this.
Do you have a better idea to make audio.py get train.py calculated the value of `mel_normalize_mean`?

**Comment by leijue222** [comment]
I stopped and set `multi_speaker=False`, then I run train.py failed with error:  
[AttributeError: 'NoneType' object has no attribute 'repeat'](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/modules/classifier.py#L67)

**Comment by leijue222** [comment]
Model result of 1.0_loss-17-0.123
example 1: `(english-ljs.wav)`
`Different models expect different lines, some have to specify speaker, language.`
example 2: `(chinese-biaobei.wav)`
`jìsuànjī dàxué zhǔyào xuékē shì kēxué hé jìzhúbù， xuéshēng kěyǐ huòqǔ jìsuànjīkēxué hé jìzhú de běnkē xuéwèi`
So far, training has exceeded 10 hours. But these two results English is not English, Chinese is not Chinese.
I must make a wrong setting, maybe I shouldn't set `ph=""`. 
I should have phonemized_text and use phonemized_text to train rather than pinyin or English words.
[wav.zip](https://github.com/Tomiinek/Multilingual_Text_to_Speech/files/5473411/wav.zip)

**Comment by Tomiinek** [comment]
Hello again,

> Is this the right way to add parameters manually? I feel a bit silly my way.
> Because train.py calculated the values successfully, but audio.py can't get the values, I will get an error of type object 'Params' has no attribute 'mel_normalize_mean'. So I have to add these two parameters manually.

It should work this way, but I think you should figure out what is happening and why the original code does not work.
Can you please post here the whole stack trace?  The function from `audio.py` has to be called from `train.py` ...

The training should take more than 10 hours. I do not remember exactly, but let's say 25k training steps with properly set guided attention decay should be enough.

The samples are a good start, isn't it? I can recognize some of the English words ... How about the attention plot? Once a sharp "diagonal" is established, victory is yours.

**Comment by leijue222** [comment]
The whole stack trace:
![4](https://user-images.githubusercontent.com/30276789/97854139-02f44580-1d34-11eb-826a-befa7936f9fc.png)
I'm sorry to bother you so many times.
You're right. The samples are a good start. For English, it can recognize some of the English words.
But pinyin is equivalent to a syllable combination, plus the tone, the data should be sparse.
Therefore, use phonemes maybe better.  
I am reprocessing the data now, try to use the phonemes.
And I refer to your suggestions in other issues and perform the following operations on the data:
```
find "wavs" -name '*.wav' | while read f; do
	echo "*"
    sox "${f}" tmp.wav gain -n -3 && mv tmp.wav "${f}"
done  
```

**Comment by leijue222** [comment]
Do you use phonemes when training Chinese and LJSpeech?
When I generate phonemes I got another error of:
```
RuntimeError: espeak not installed on your system
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\software\\anaconda3\\envs\\tts\\lib\\site-packages\\epitran\\data\\map\\chinese.csv'
```

**Comment by leijue222** [comment]
Oh, NO...
I set `use_preemphasis=True` after regenerating the spectrogram. I have to spend a few hours to regenerate spectrogram again. . .

**Comment by leijue222** [comment]
Note about my training steps:
Dataset: **LJSpeech**: 13,100 English audio clips | 24 hours | one woman speaker
                  **Biaobei**: 10,000 Chinese audio clips | 12 hours | one woman speaker
1. Use sox to uniformly normalize audio files and resampling to 22050.
2. Wirte function to load my dataset implement it in the file loaders.py. Then, organize the train.txt and val.txt by TextToSpeechDataset.create_meta_file(set use_phonemes=True and use_preemphasis=True before do it, train.txt : val.txt = 9 : 1).
3. Params.py setting:
******************* DATASET SPECIFICATION *******************
dataset = "zh_en"
languages = ['zh', 'en']
balanced_sampling = True
perfect_sampling = True 
*************************** TEXT ****************************
use_phonemes = True
******************** PARAMETERS OF AUDIO ********************
use_preemphasis = True
******************** PARAMETERS OF MODEL ********************
encoder_type = "generated"    # In your website samples, I thought generated type is the best!
generator_dim = 2                
generator_bottleneck_dim = 1
multi_speaker = False       # Two languages, each language has only one speaker
speaker_embedding_dimension = 32 #If each language has 10 speakers, what should this value be?
multi_language = True
language_embedding_dimension = 2
input_language_embedding = 2

**Comment by Tomiinek** [comment]
Hello,

> I withdrew the whole stack trace image because there is a simple solution: using Ubuntu to train is a wise choice.
> In Win10, there are two compatibility problems:
>  1. audio.py can't get the parameter of mel_normalize_mean.
>  2. Unable to solve the compatibility problem caused by espeak when using TextToSpeechDataset.create_meta_file to generate phonemes under Win10.

Ah, I am sorry for this inconveniece. I have unfortunately no experience with running on Win10. Good point though! Thank you.

> Wirte function to load my dataset implement it in the file loaders.py. Then, organize the train.txt and val.txt by TextToSpeechDataset.create_meta_file(Note set use_phonemes=True and use_preemphasis=True before do it; train.txt : val.txt = 9 : 1).

Just a note, do phonemes reflect the tones as pinyin?

> Could you please help me recheck my parameter settings?
> Especially the Model parameters with *, I can't ensure their size from the code comments.

Sure, I think that the generated model does not use the `language_embedding_dimension` parameter at all, so do not care about that. This parameter is replaced by `generator_dim`, and 2 or 3 is reasonable, as you have just 2 languages. `generator_bottleneck_dim` should be less than `generator_dim`, I would choose 1. You have hot 20 speakers in total, so something like 16 should hopefully be ideal for `speaker_embedding_dimension`. Other mentioned parameters are ok.

**Comment by leijue222** [comment]
> Ah, I am sorry for this inconvenience. I have unfortunately no experience with running on Win10. Good point though! Thank you.
I chose WIN10 due to the lack of Ubuntu hard drives capacity. Generally, people will not train under WIN10, after all, many compatibility problems cannot be avoided. 

> Just a note, do phonemes reflect the tones as pinyin?

Yes, I refer to your code, use jieba and pinyin package convert Chinese into pinyin, and then generate phonemes.

> Other mentioned parameters are ok.
Thank you very much!  
And I remember you gave a nice reference before for voice cloning and code-switching:

> Add more speaker for each languages: such as add 20 speaker for each languages;
> and each speaker not have to have a lot of examples for each speaker: 50 transcript-recording pairs per speaker can be ok. 

But my current data is a bit relative compared to your suggestion.
*************************** COMPARE ****************************
                                     Number of speakers in each language     |      Number of audio per speaker
My situation                                              1                                                                zh:10,000      en:13,100
Your suggestion                                10 or 20                                                                        50 is ok

Training 50K steps is a long process. Hope I can have a good result when code-switching between en and zh. 
If the result is not good, then I have to rearrange the data: increase the number of speakers, reduce the number of audio for each speaker.

**Comment by leijue222** [comment]
```
language: en and zh 
speaker: `en-ljs` and `zh-biaobei`
```
New progress!
Example of only English: `en-ljs-79.wav` and only Chinese: `zh-biaobei-79.wav`
> Text: As a result of the infusion of liquids through the cutdowns, the cardiac massage, and the airway 
Order: {Text}|en-ljs|en
> Text: huángyù línghǎn yǎ le hóulóng， juéwàng dì tānzuò zài dìshàng。
Order: Text|zh-biaobei|zh

These two pronunciations are relatively correct, and they should be better if they are processed by WaveRNN.

Example of clone speaker voice of  `zh-biaobei` 

> Text: As a result of the infusion of liquids through the cutdowns, the cardiac massage, and the airway,|zh-biaobei|en
Order: {Text}|zh-biaobei|en

Example of code-switching: `zh-en-mix.wav`

>Text: huángyù línghǎn yǎ le hóulóng，As a result of the infusion of liquids through the cutdowns,
Order: {Text}|zh-biaobei|zh-10,en-10,zh

As you said, both code-switching and voice-cloning are failed.

**Comment by Tomiinek** [comment]
If I were you, I would definitely use as much langauges and speakers as possible. It will definitely improve both - English and Chinese and you can just throw them away during inference. So incorporating English into the provided datasets is IMHO great idea. You can use the TUNDRA dataset, there are more languages with just a little data and it includes also English and it is segmented similarly as CSS10.

No I did not use phonemes, but I used preemphasis. It slightly improves the synthesis when using Griffin-Lim, but if you use WaveRNN or something like that, it does not seem to be important.

**Comment by leijue222** [comment]
Now there are new developments, I want to share with you.
Just use LJSpeech and Biaobei is successful in code-switching! 
English pronunciation is pretty good! But Chinese is a little defect:
     1. Different languages have different voices, and there cannot be only one voice. 
     2. Chinese tones are not accurate, just like Chinese beginners can't distinguish the tones. Can understand, but inaccurate tones. Like the model does not learn tone information.

**Comment by leijue222** [comment]
Hi, @Tomiinek Thanks very much. 
There is good progress that I succeeded in code-switching, but the Chinese pitch is too weird.
![F51E1768F344703800B0625C9C7FC366](https://user-images.githubusercontent.com/30276789/98636291-8845ae80-2361-11eb-9680-a4fb03e4ddf9.png)
Ground truth mel obviously has a slope, but what I generated is flat, so the pitch will be different

Does Params.py have any parameters that affect the pitch?

**Comment by Tomiinek** [comment]
Great plot :+1: 

Well, you can try adding tone labels explicitly as an input (and use for example stresses in English encoder). But the code does not include this extension, so you would have to add it yourself.
We have already discussed this in #11

**Comment by leijue222** [comment]
> Great plot 
> 
> Well, you can try adding tone labels explicitly as an input (and use for example stresses in English encoder). But the code does not include this extension, so you would have to add it yourself.
> We have already discussed this in #11

Tone label is a  good idea. 
What made me excited is your [example](https://colab.research.google.com/github/Tomiinek/Multilingual_Text_to_Speech/blob/master/notebooks/code_switching_demo.ipynb). Input pinyin, and the output audio is correct(My failed case in your pre-trained model, the tone is all right).
You tell me tones are not supported, but your model Chinese tone is right. 
I can't figure it out; it's too weird.

**Comment by Tomiinek** [comment]
> You tell me tones are not supported, but your model Chinese tone is right.

I used directly grapheme inputs and Chinese was a low-resource language. Pinyin has explicitly tone marks above characters, so the model probably understands them. Some of them are shared with French, such as é and è, but it does not seem to be a problem. 

I cannot distinguish tones very well (even though I completed a few Chinese lectures in Duolinguo :smile: ), so I am happy to hear that it works in the demo :smile: 

You are using phonemes, right? Can you show a few examples of your phonemicized Chinese sentences?

**Comment by leijue222** [comment]
> You are using phonemes, right? Can you show a few examples of your phonemicized Chinese sentences (I mean the IPA representation)?

Of course！Here:
```
000004|zh-biaobei|zh|zh/biaobei/wavs/000004.wav|spectrograms/013103.npy|linear_spectrograms/013103.npy|dèngxiǎopíng yǔ sāqiēěr hùiwù。|tə5ŋɕjɑu2phiɜŋ ʲy2 sɑ5tɕhiɛ5ər2 xu5i1wu5。

LJ001-0001|en-ljs|en|en/ljspeech/wavs/LJ001-0001.wav|spectrograms/000000.npy|linear_spectrograms/000000.npy|Printing, in the only sense with which we are at present concerned, differs from most if not from all the arts and crafts represented in the Exhibition|pɹɪntɪŋ, ɪn ðə əʊnli sɛns wɪð wɪtʃ wiː ɑː at pɹɛzənt kənsɜːnd, dɪfəz fɹɒm məʊst ɪf nɒt fɹɒm ɔːl ðə ɑːts and kɹafts ɹɛpɹɪzɛntɪd ɪn ðə ɛksɪbɪʃən
```
[all.txt](https://github.com/Tomiinek/Multilingual_Text_to_Speech/files/5523919/all.txt)
This is all the supervised data that I trained to generate with [create_meta_file](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/dataset/dataset.py#L193).

2. I used the CommonVoice dataset and the English dataset for training（EN：9speaks，ZH：8speaks，each speaker 80~180 audio files, not phonemes, use your default param json）, but I didn't get good results, especially in English, and the pronunciation was incorrect. I did not delve into the problem in this regard. Maybe I should add CSS10 dataset.
I have asked many questions, and I have disturbed you to a certain extent. I hope you don't mind. But your work is really good, so I really want to reproduce your effect in both Chinese and English.

**Comment by Tomiinek** [comment]
Hello again :slightly_smiling_face: 

> I am using your code to train pure Chinese (using phonemes) ...

Hmm, look at the phonemicized variants. I cannot read tone from them. For example `phiɜŋ` can correspond both to 俜 or 瓶 (I don't know what does it mean, I just used a pinyin convertor), so it might be challenging for the model to guess the right tone just from a sentence or context, isn't it?

> use phonemes | succeed in code-switching, | problem is Chinese tones are often inaccurate | 50K steps

So this is not surprising for me.

> use zh-pinyin and en-words | succeed in code-switching | problem is Chinese tones are not inaccurate and whole quality is not as good as 1 | 50K steps

But this is surprising :smile: ... What data did you use?

> use CommonVoice, add one zh speaker(100+ audio files), add 9 en speaker(100+ audio files) | problem is English pronunciation is wrong | 300 epochs

Common Voice itself is really small, you should include also CSS10.

> To be honest, I am a little powerless now.

Don't give up! :+1: 

> Maybe I should make the final fight, use your default code-switching parameters, not phonemes, use the five languages in css10 and CommomVoice, delete one of them (keep German), and add English. English speakers can be a bit more, and Chinese speakers can be added with a biaobei speaker with 10,000 audio files(I don't know if there are so many audio files for a speaker. After all, other speaker only about 100 audio files.).

This definitely make sense. We have already discussed it here #29 

> I got another idead of change input, replace pinyin with consonant + tone. I will share with you if I make progress.

Could you please describe the idea in other words? Tones are coupled with vowels? so I do not understand ...

**Comment by leijue222** [comment]
> For example phiɜŋ can correspond both to 俜 or 瓶

It turns out that some phonemes synthesized by `phonemizer package` have no tones. . .

> But this is surprising 😄 ... What data did you use?

 I told [before](https://github.com/Tomiinek/Multilingual_Text_to_Speech/issues/27#issuecomment-719874655), just LJSpeech and Biaobei.

> Could you please describe the idea in other words? Tones are coupled with vowels? so I do not understand ...

Give an example, it’s a bit difficult to describe. 
The annotation of the Chinese Biaobei dataset like `ka2 er2 pu3`, some people will process `ka2 er2 pu3` into `k a2, er2 pu3`. In Fastspeech2, some people will complete this process through MFA, and also can write code conversion(The [baker.py](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/processor/baker.py) file of TensorFlowTTS has this conversion process)

> Don't give up!

Thank you brother, I will try my new ideas

**Comment by leijue222** [comment]
Hi, brother.
I changed different input again to listen to the result of your pre-trained model in [colab](https://colab.research.google.com/github/Tomiinek/Multilingual_Text_to_Speech/blob/master/notebooks/code_switching_demo.ipynb). With speaker of `00-zh, 01-zh, 02-zh, 03-zh, 05-zh, 06-zh`.
**The pitch accuracy is really satisfying!** But the disadvantage is that the sound quality is a bit poor such as noise, vibrato.
Do you know the reason for the poor sound quality? Is the dataset of each zh speaker not enough?
If it is, I have an idea to add another zh speaker, use the dataset of Biabei(10,000 Chinese audio clips | 12 hours | one woman speaker). What do you think?

**Comment by leijue222** [comment]
Hi, @Tomiinek 
I figured out why the pitch is inaccurate because the parameter string lacks numbers!
I change character https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/params/singles/zh.json#L4
to
`"characters": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890",`
Then the tone is right!

Here is samples：[zh_sample.zip](https://github.com/Tomiinek/Multilingual_Text_to_Speech/files/5695867/zh_sample.zip)
I use the symbol `-` to represent the end of a syllable, and `/` to represent the participle.
```
s.wav
k a 2 - er 2 - p u 3 / p ei 2 - w ai 4 - s un 1 / w an 2 - h ua 2 - t i 1 / 。

s1.wav
b ao 2 - m a 3 / p ei 4 - g ua 4 / b o 3 - l uo 2 - an 1 / ， d iao 1 - ch an 2 / y uan 4 - zh en 3 / d ong 3 - w eng 1 - t a 4 / 。

s2.wav
z ai 4 / y u 4 - zh ong 1 / ， zh ang 1 - m ing 2 - b ao 2 / h ui 3 - h en 4 / j iao 1 - j ia 1 / ， x ie 3 - l e / y i 2 - f en 4 / ch an 4 - h ui 3 - sh u 1 / 。
```

`s1.wav` and `s2.wav` is all right! But `s.wav`, I don't understand why `p u 3` made sounds two times.

**Comment by Tomiinek** [comment]
Congratulations! :partying_face: 

> Why don't you restrict the range of mel to [-4,4], which is the normalization of mel. This can more effectively speed up the convergence and improve the results. I have not yet made normalized changes to your project.

Good question :slightly_smiling_face: I just decided to normalize it in this way without experimenting.

I do know that some other implementations use the normalization to [-4, 4] and argue that it improves results over normalization to [-1, 1] or [0, 1]. I really dislike the magical constant 4 and the way of normalization and I haven't found any paper describing it or proving that it really is what I want. Thus I use somehow standard normalization used for images ...

I am convinced that normalization is important and that:
- Mean over data should be 0, as if an output neuron is not activated and biased at all, it just produces mean value which is a pretty good start (and the standard deviation also makes sense to me). Everything is kept in reasonable ranges.
- Normalization of all mel bands in the same way is weird (e.g. taking max value and min value and scaling all spectrograms to this range uniformly), because we expect values with different statistics in different frequency bands (for example, suppose that the 80. mel band is oxtraordinary and always very low like -10000000, so let's make it zero so it is easy for the network to predict it).

What do you think about that?

**Comment by leijue222** [comment]
It can be understood this way. Because the prediction mel is doing regression, the MSE loss function is used, which is equal to 80 dimensions. The prediction of each dimension is independent, and the loss value is equal to the weighted value. The weight of each dimension is positively related to its own value. This leads to the larger the value of the dimension, the greater the impact on the loss value, the smaller the value may not be able to learn. For example, the two predicted values of [1000, 0.01] are changed by 10% each, and the loss value is similarly changed by 100+0.001. You can see that the small value can be ignored. If the value of 1000 is always poorly learned, then the loss value is Will fluctuate in this dimension, and cannot pay attention to the 0.01 dimension. Normalization equals that the weight of the loss function is 1, so that the model pays equal attention to each output. Because the predictions are all logmels, there is a large difference in values. The absolute value of the low-frequency dimension may be smaller, and the high-frequency dimension is much larger, so normalization is required.

And talk a trick about pause:
The quality of open-source data sets is not high enough, and the pause time of some data sets is short, which makes it difficult for the model to learn the pause naturally from punctuation. Therefore, normalization is also more convenient to add silent Mel control punctuation pause. For example, I want to synthesis 2 minutes of audio, split long sentences into short sentences based on punctuation, and add mute Mel when splicing to complete the synthesis of long sentences. (If normalized to [-4,4], the value of the mute end Mel is -4, which is more controllable)

**Comment by leijue222** [comment]
`Thank you for your constructive comments. d eng 4 - x iao 3 - p ing 2 / y u 3 / s a 4 - q ie 4 - er 3 - are good friends do you know?|en-ljs|english-41,chinese-62,english`
https://user-images.githubusercontent.com/30276789/102761078-60f6ee00-43b1-11eb-8c69-1a4de83182f5.mp4

It's a success for zh-en mixed TTS. A drawback is failed the voice clone.
Add more speakers for each language, then the output audio will just have one speaker voice?

**Comment by Tomiinek** [comment]
Hello!

Unfortunately, I cannot play the audio from the previous post.

Well, if the model encounters just one or a few speakers for each language, it cannot learn the difference between language and voice characteristics and is not able to disentangle them (if you provide more speakers, the model can no longer explain the variation of voices by the language embedding and figures out that speaker embeddings are the thing it should rely on). Thus the change of language also changes voice. The components of the model try to fight this issue, but you still need several training speakers for each language. Another approach is to use phoneme inputs and remove the input language embeddings at all.
