### ISSUE TITLE
About Generate Convolution Encoder

### ISSUE THREAD

**Issue by YihWenWang** [Tomiinek/Multilingual_Text_to_Speech#30]
Hello, I have a problem with the encoder of the synthesizer.
Do you have used the original encoder in Tacotron-2 that including Convolution and LSTM?
Why do you use Convolution and Highway Convolution in encoder?

Thanks.

**Comment by Tomiinek** [comment]
Hello!

First, the original encoder is implemented here: https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/modules/encoder.py#L9-L45

and it does not contain highway convolutions.

The generated encoder is based on a fully convolutional encoder without LSTMs, implementation is here: https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/modules/encoder.py#L100-L130

It follows the architecture from the paper [Efficiently Trainable Text-to-Speech System Based on Deep Convolutional Networks with Guided Attention](https://arxiv.org/abs/1710.08969). The encoder is much deeper than the original one with LSTMs, so the highways support gradient propagation to the very beginning of the encoder and enable the model to converge.

**Comment by YihWenWang** [comment]
Thanks for your reply.
Could it cause a problem of noise or pronunciation about this model change?
Because my English-Mandarin TTS model sometimes has this problem.
Did this problem have related to speaker embedding?
Because I extra use the speaker encoder module in order to get speaker embedding.

**Comment by Tomiinek** [comment]
Hm, I do not think so.

**Comment by leijue222** [comment]
@YihWenWang, Hi.
Do you use this project achieved TTS that can speak both Chinese and English?
In fact, I have made many attempts, use the baker and LJS dataset to train or use just the baker dataset to train.

The baker dataset is absolutely no problem, I already use it achieved Chinese, there is a wav [sample](https://github.com/begeekmyfriend/tacotron2/files/5670612/wav_sample.zip)

But I can't understand why I use this project, all the trained model can't pronounce the correct Chinese tone(Just like a foreigner who just learned Chinese).

Could you give me some advice?
