### ISSUE TITLE
WaveRNN Dataset format

### ISSUE THREAD

**Issue by sooftware** [Tomiinek/Multilingual_Text_to_Speech#31]
Hi Tomiinek!!  
I'm sorry I seem to ask you questions all the time.   
I'm so interested in your project that much, so please understand!  
  
I'm going to train the WaveRNN model to fit my dataset.  
But I couldn't find any words in your WaveRNN repo about the format in which to configure the dataset format.  
  
Can you give me any advice on how to configure dataset formats or give me relevant materials?
  
Thank You!!

**Comment by Tomiinek** [comment]
Hello :slightly_smiling_face: 

No problem!

First, set hyper-parameters in `hparams.py` ... you might be interested in `data_path`, `voc_mode`, `bits` and `mu_law` (but please go through issues in the original repository, there are some good hints and conversations about convergence etc.) 

Then use the `preprocess.py` file. To run it, you need a directory with directories for each language, i.e. `de`, `fr`, ... 

Each of these language-specific directories should contain two directories named `wavs` and `gtas`. The `wavs` directory should contain all the `.wav` files of the particular language in dataset. The `gtas` directory should contain ground-truth aligned spectrograms of the corresponding `.wav` files with the same filename, but `.npy` extension. These GTA spectrograms can be generated using the `gta.py` script in this repository. 

Then run the `preprocess.py` where `--data_root` is the base directory containing language-specific directories, `--inputs` is a list of names of the language-specific directories, and `--output` is an output directory. The script will generate `mel` (GTA spectrograms in a way which is supported by the model) and `quant` (quantized audio files which are used as targets during training, so it is needed to re-generate files if you change the parameters mentioned above) directories and a metafile `dataset.pkl` in the output directory. 

That is hopefully all :partying_face: 

(I do not remember details precisely, so I am sorry if something I said is not true :smile: )

**Comment by sooftware** [comment]
Thank you for always giving me a good answer, Tomiinek!!
