### ISSUE TITLE
WaveRNN's not learning well.

### ISSUE THREAD

**Issue by sooftware** [Tomiinek/Multilingual_Text_to_Speech#33]
Hi Tomiinek!!  
I used your WaveRNN Repo to train vocoder.   
I've formatted the data, I've trained WaveRNN, but I haven't been able to produce a voice at all.  
  
Is the hyperparameter the same as the one at hparams.py when you train your model?

**Comment by sooftware** [comment]
I made wave with your wavernn.pyt using mel from preprocess.py, but it didn't work.  
I wanna know feature setting when trained wavernn.

**Comment by Tomiinek** [comment]
Hello :slightly_smiling_face: 

I think I used the same parameters as in the file. But it converged really really slowly and I think that the results could be much better. I would maybe suggest you using a different vocoder, but I do not have much experience with them.

**Comment by sooftware** [comment]
Thank You!! I will try it!!
