### ISSUE TITLE
AssertionError: Validation set contains speakers which are not present in train set!

### ISSUE THREAD

**Issue by gtLara** [Tomiinek/Multilingual_Text_to_Speech#34]
I am trying to train the system on CSS10 dataset and and receving the error stated in the title of this issue. 

The error is raised following the training command `PYTHONIOENCODING=utf-8 python3 train.py --hyper_parameters generated_switching` as instructed in the documentation. I have downloaded all languages of CSS10 and  changed the dataset parameters in params.py file as such:

```
   ******************* DATASET SPECIFICATION *******************
 
  4     dataset = "css10"                 
  3     cache_spectrograms = True  
  2     languages = ['zh', 'fi', 'de', 'el', 'hu', 'ja', 'kss', 'ru', 'es', 'fr', 'nl']              
44     balanced_sampling = False          
  1     perfect_sampling = False            
```

I have also preprocessed all the spectrograms with the prepare spectrograms file. I do not understand where I went wrong in following the documentation. I understand the error but not it's cause and supressing it in the code does not work. Can anyone help?

**Comment by leijue222** [comment]
You can use [generated_training.json ](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/master/params/generated_training.json) as hyper_parameters to train.
