### ISSUE TITLE
Unable to find the procedure to retrain the WaveRNN vocoder

### ISSUE THREAD

**Issue by yocel1** [Tomiinek/Multilingual_Text_to_Speech#36]
Hello,

I passed a lot of time to try to understand how the WaveRNN by Tomiinek works to retrain it by myself but I failled.
The documentation is not done and I tried a lot of things...

For the moment I am blocked after generate the GTAs because I am not able to link a GTA file to a WAV file.

Can you help me please ?

Thanks

**Comment by Tomiinek** [comment]
Hello @yocel1! Have you already read the issues  #31 and #31?

**Comment by yocel1** [comment]
Hello @Tomiinek ,

Thanks for your quick answer and for this project.
yes I read it but I dont undestand how to link my WAVs and the GTAs.
I generate the GTAs, I create subfolders for each speacker and sort it by this way but how to determine witch one GTA file is link to one WAV file ?

NB: in my case I trained the GENERATED_SWITCHING with 5 languages.

**Comment by Tomiinek** [comment]
I think it was already answered:

> Each of these language-specific directories should contain two directories named wavs and gtas. The wavs directory should contain all the .wav files of the particular language in dataset. The gtas directory should contain ground-truth aligned spectrograms of the corresponding .wav files with the same filename, but .npy extension. These GTA spectrograms can be generated using the gta.py script in this repository.

It means that they are linked via the combination of the contained directory and their name without extension.
The code which does the linking is [here](https://github.com/Tomiinek/WaveRNN/blob/ad74b037b919f01e1e9dc87ba2585fa65b7f6420/preprocess.py#L28-L41).

**Comment by yocel1** [comment]
OK with that but how can I associate the .npy GTA files generated by the gta.py script with my .wav file because they do not have the same name?

**Comment by Tomiinek** [comment]
I see now :slightly_smiling_face: The `gta.py` script goes through a dataset in order without shuffling, so the the GTA file with the lowest ID corresponds to the `.wav` file from the first line of the corresponding dataset meta-file and so on ... 

I know it is not ideal, but it should be possible to link the files with some shell one-liner.

**Comment by yocel1** [comment]
OK I found a procedure but after some hours I see I have to restart my train with the "perfect_sampling" parameter at false.
I will return you my results if it works beter.

**Comment by yocel1** [comment]
It works without these parameters

**Comment by Anhar2** [comment]
Hi, 

How could I generate GTA spectrograms themselves? 

I trained the original Multi=speaker model and I have the original spectrograms and linear spectrograms used for the training and the model weights after training on Arabic dataset

Now, how can I produce the gta files? 
Thank you in advance :)
@Tomiinek 
@VoxFurem

**Comment by Tomiinek** [comment]
Hey @Anhar2 , fortunately. I received you email :slightly_smiling_face: 

> I see now slightly_smiling_face The gta.py script goes through a dataset in order without shuffling, so the the GTA file with the lowest ID corresponds to the .wav file from the first line of the corresponding dataset meta-file and so on ...
> I know it is not ideal, but it should be possible to link the files with some shell one-liner.
 
The `gta.py` script should work for you. Or do you have a problem running the script?
