### ISSUE TITLE
[Question] About Generated Encoder

### ISSUE THREAD

**Issue by sooftware** [Tomiinek/Multilingual_Text_to_Speech#38]
Hi Tomiinek!! I have a question about Generated-Encoder.  
As I understand, After training, Generated-Encoder's fully-connected layer becomes a dictionary.   
{Key: language id embedding, Value: Conv or batch-norm's weight}. Right??  
  
If so, rather than generating weight by fully-connected layer, it's better to fix weight by language and use it, don't you?    
If not, is there a case where weight is changed by other elements other than language after training?  
  
Thank You!!

**Comment by Tomiinek** [comment]
Hello, I am sorry for a late response, but I missed your post :cry: 

You are right, it is just a fixed mapping from language IDs to weights.
After training, it is of course better to fix the weights and use them. What the the model does during inference is actually very similar. It first generates the weights for the languages that appear in the synthesized sentence and then use them for generating the encoder outputs in parallel.

**Comment by sooftware** [comment]
Thank you @Tomiinek !!  
Your answer is a lot of help to me.
