### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by kongziyue1234** [Tomiinek/Multilingual_Text_to_Speech#42]
Hello，this project is very nice and thank you for your share!
There is an error when I run train.py: RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)
![image](https://user-images.githubusercontent.com/58846490/109385414-99c1bf00-792e-11eb-9202-c77e0dde8faf.png)
Environment: The system is win10,  and other environments are consistent with requirement.txt
I don't know what causes this problem .Is it a problem with win10 system or I need to change the code?

**Comment by Tomiinek** [comment]
Hello, thank you for reporting the error. 

I cannot reproduce the issue, could you try to replace  [this line](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/83b1164e9d385742558b8b0171568816e7f51e44/modules/tacotron2.py#L145) with the following code: 
``` python
embedded = layer(encoded if condition is None else condition.long())
```
 Does it help?

**Comment by kongziyue1234** [comment]
Hello，thank you for your suggestion.
I tried your suggestion, but the mistake still came up.Later, I conducted the experiment in Ubuntu system, and such an error occurred after a warning:audio amplitude out of range, auto clipped. appeared
![image](https://user-images.githubusercontent.com/58846490/109803385-ef160d00-7c5b-11eb-8459-6fd5ac993742.png)

**Comment by Tomiinek** [comment]
Hello, I have never seen the error. I am also getting the warnings, but they do not cause any errors. 

After some googling, it seems to me like an issue with your X server or drivers.
It is probably not related to the code.

**Comment by kongziyue1234** [comment]
Hello,I switched the experiment to different gpus and the problem was solved.However, in the half of the training, the following mistakes occurred.I have updated the tkinter package and reduced the batch_size,but they didn't work. Have you ever encountered them?
![image](https://user-images.githubusercontent.com/58846490/111063579-8005a780-84ea-11eb-9814-db64cab2b913.png)
![image](https://user-images.githubusercontent.com/58846490/111063781-919b7f00-84eb-11eb-80b2-2bcb45718c13.png)

**Comment by michael-conrad** [comment]
Add the following to the top of the train python script

```python
import matplotlib
matplotlib.use("Qt5Agg")
```
