### ISSUE TITLE
Using the NPY output with a different vocoder?

### ISSUE THREAD

**Issue by michael-conrad** [Tomiinek/Multilingual_Text_to_Speech#44]
Is it possible to use the saved npy output files with a different vocoder?

If yes, are there any special steps required for shaping, etc?

**Comment by Tomiinek** [comment]
Hello,
do you have any specific vocoder in mind?

You can of course use arbitrary algorithm capable of inverting mel spectrograms (i.e., vocoders such as WORLD are not suitable).
The output files are (hopefully) standard log-magnitude mel spectrograms of shape `[num_mels, time]`.

**Comment by michael-conrad** [comment]
I see references to MelGAN, WaveGAN, WaveGlow, HiFi-GAN, etc. And would like to compare outputs with a couple of the newer ones.

**Comment by Tomiinek** [comment]
Ok and what is the question or problem? :smile: 
I think there shouldn't be any problem with using these vocoders.
