### ISSUE TITLE
synthesize problem

### ISSUE THREAD

**Issue by kongziyue1234** [Tomiinek/Multilingual_Text_to_Speech#45]
Hello,when I synthesized a sentence,a problem occurred
![image](https://user-images.githubusercontent.com/58846490/113661508-d2487b80-96d8-11eb-8576-acc235f8cdeb.png)
I tried another sentence ,the same problem occurred again
![image](https://user-images.githubusercontent.com/58846490/113661677-1f2c5200-96d9-11eb-8989-5ee2598d64ac.png)

**Comment by michael-conrad** [comment]
See pull request #46 for a fix.

**Comment by kongziyue1234** [comment]
I got it,thank you for your help!
