### ISSUE TITLE
Train with a small number of speakers

### ISSUE THREAD

**Issue by ductho9799** [Tomiinek/Multilingual_Text_to_Speech#49]
My purpose is to make a Vietnamese Speech Synthesis model be able to pronounce English.

But, I have just a Vietnamese dataset with 2 female speakers (13100 and 16500 utterances ~ around 50-55 hours).
I want to train this dataset with LibriTTS with 127 female speakers(~ 58 hours).

Do you have any suggestions for my experiments?

**Comment by Tomiinek** [comment]
Hello, good luck :slightly_smiling_face: 

Use as many languages as you can (ideally the data I provide here) and add some English and Vietnamese. I think that a few Vietnamese voices are now even in [Common Voice](https://commonvoice.mozilla.org/en/datasets), so you can include them too. It should help to disentangle speakers and languages.

**Comment by gbaian10** [comment]
@Tomiinek 
I also tried two languages and set multi_language in params.py to True.
But it have an error.
```
    one_hots = torch.zeros(languages.size(0), languages.size(1), hp.language_number).zero_()
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

I don't understand what (languages.size(0), languages.size(1), hp.language_number) is? 
Even though I changed 1 to -1, it still got an error on the next line

https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/master/dataset/dataset.py#L303
one_hot? one_hots? Are they the same thing?
