### ISSUE TITLE
Any paper of this work available?

### ISSUE THREAD

**Issue by YuewenC** [Tomiinek/Multilingual_Text_to_Speech#5]
Very interesting paper! Wondering any paper of this work available:)

**Comment by Tomiinek** [comment]
Hi! Thank you for your interest, detailed description is on the way, stay tuned. Or contact me on email (you can find it via my profile) and I wil send you a more details in reply :sunglasses:

**Comment by singhaki** [comment]
Hi Tom, Have you posted a detailed description somewhere?

**Comment by Tomiinek** [comment]
Hi @singhaki ! Hopefully, there will be something available in the next three weeks.

**Comment by Tomiinek** [comment]
A short paper with description is now available [here](https://arxiv.org/abs/2008.00768)!
