### ISSUE TITLE
Integrate a new language

### ISSUE THREAD

**Issue by MathieuRS1** [Tomiinek/Multilingual_Text_to_Speech#53]
Hello and first of all thank you for your work!

What would be the steps to add a language? In this case French from France (and not from Quebec).

Can I use the result from this Training colab ?

https://colab.research.google.com/drive/14X73UiywnoL9VS30iPDcX4WXxwZWv2e2

Thank you! :)

**Comment by Tomiinek** [comment]
Hello,

> What would be the steps to add a language? In this case French from France (and not from Quebec).

Add your data to the dataset and re-train the model.

> Can I use the result from this Training colab ?

Not really, I think you have to train the model again from scratch.

**Comment by MathieuRS1** [comment]
Hi,

Ok thanks =)
