### ISSUE TITLE
could you tell me where's the pretrained models? Thanks.

### ISSUE THREAD

**Issue by YoungChanYY** [Tomiinek/Multilingual_Text_to_Speech#59]
Where can I download the pretrained model? "https://github.com/Tomiinek/Multilingual_Text_to_Speech/releases/download/v1.0/$tacotron_chpt" I cann't find this file path now.

Thanks very much!

**Comment by YoungChanYY** [comment]
i got the pretrained model successly now from "https://github.com/Tomiinek/Multilingual_Text_to_Speech/releases/download/v1.0/generated_switching.pyt" .

**Comment by Tomiinek** [comment]
Hello, you can find all resources and checkpoints in the [release here on Github](https://github.com/Tomiinek/Multilingual_Text_to_Speech/releases).
