### ISSUE TITLE
colab demo does not work

### ISSUE THREAD

**Issue by raymond00000** [Tomiinek/Multilingual_Text_to_Speech#61]
Hi,

I tried to run the colab demo, but it did not work.
Likely because the code on using WaveRNN is not updated. i.e. 

below codes are not longer existed at the latest WaveRNN.

     from models.fatchord_version import WaveRNN
     from utils import hparams as hp
     from gen_wavernn import generate
 
Many thanks if you could update accordingly.

**Comment by Tomiinek** [comment]
Hello, thank you for reporting the issue! :+1: I did not notice ... 
Both notebooks are fixed, check it out (and clear cache in case it does not work).
