### ISSUE TITLE
Are the different values for fft bins intentional between WaveRNN and this project?

### ISSUE THREAD

**Issue by michael-conrad** [Tomiinek/Multilingual_Text_to_Speech#64]
Are the different values for fft bins intentional between WaveRNN and this project?

I see in this project:

```python
num_fft = 1102
```

but I see in WaveRNN:

```python
n_fft = 2048
fft_bins = n_fft // 2 + 1
```

1102 vs 1025 ?

**Comment by Tomiinek** [comment]
Ou this is not intentional, but it seems that `n_fft` or `fft_bins` are not used anywhere. They were probably used in the original WaveRNN repo which included a TTS part producing spectrograms for the WaveRNN. Am I right?

**Comment by michael-conrad** [comment]
Are not the n_fft and fft_bins values used for spectrogram creation?

I see the following in `dsp.py` in the WaveRNN repo:

```python
def stft(y):
    return librosa.stft(
        y=y,
        n_fft=hp.n_fft, hop_length=hp.hop_length, win_length=hp.win_length)
```
