### ISSUE TITLE
WaveRNN - instructions for setup for training are invalid

### ISSUE THREAD

**Issue by michael-conrad** [Tomiinek/Multilingual_Text_to_Speech#65]
The dependent WaveRNN repository does not contain valid instructions for training a vocoder from scratch.

It references CLI options which don't exist and indicates that train_tacotron.py (not part of the repo) is to be used to create the preprocess gta files.

Attempting to run scripts/preprocess.py results in:

```python
$ python scripts/preprocess.py --data_root ../dataset/ --hp_file ../hparams.py  --inputs en 

Traceback (most recent call last):
  File "/home/muksihs/git/cherokee-wavernn/WaveRNN/scripts/preprocess.py", line 80, in <module>
    process_data(args.data_root, args.inputs, output_dir)
  File "/home/muksihs/git/cherokee-wavernn/WaveRNN/scripts/preprocess.py", line 36, in process_data
    mel = np.load(os.path.join(data_root, d, "gtas", f + ".npy"))
  File "/home/muksihs/miniconda3/envs/cherokee-wavernn/lib/python3.9/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/en/gtas/000003662.npy'

```

(I put the ticket here as the fork doesn't have issue tracking)

**Comment by michael-conrad** [comment]
I've come up with the following to generate the needed mel files. Does this look correct to you?

https://github.com/CherokeeLanguage/cherokee-wavernn/blob/main/prepare_spectrograms.py

**Comment by michael-conrad** [comment]
Permalink:

https://github.com/CherokeeLanguage/cherokee-wavernn/blob/f9a409dd47723dd476c0dbfb2c36e28c40f9374d/create_training_files.py#L104-L129

**Comment by Tomiinek** [comment]
Hello, the instructions are just copied from the orignial repo so they are not useful at all.
Your call to `preprocess.py` looks good to me, but it is expected that you have `../dataset/` with two directories: `wavs` and `gtas` where `wavs` store your raw audio files, `gtas` are spectrograms produced by the `gta.py` script in this repository.
The preprocess script should produce two new directories: `quant` with WaveRNN targets and `mel` with WaveRNN input spectrograms (but normalized / processed in another way then in this repo).

**Comment by michael-conrad** [comment]
> Hello, the instructions are just copied from the orignial repo so they are not useful at all.
> 
> Your call to `preprocess.py` looks good to me, but it is expected that you have `../dataset/` with two directories: `wavs` and `gtas` where `wavs` store your raw audio files, `gtas` are spectrograms produced by the `gta.py` script in this repository.
> 
> The preprocess script should produce two new directories: `quant` with WaveRNN targets and `mel` with WaveRNN input spectrograms (but normalized / processed in another way then in this repo).

Yes, these conditions are met.

I created an updated "create_training_files.py" script which cleans up everything, then generates wavs, mels, then runs the WaveRNN preprocess script.
