### ISSUE TITLE
How to apply this tool to my custom Japanese data?

### ISSUE THREAD

**Issue by zzxiang** [Tomiinek/Multilingual_Text_to_Speech#68]
Hello, thanks for providing this amazing repository!

I wonder how to apply this tool to my custom data set, which contains about 8 Japanese speakers, each of them having 200 utterances. I want to synthesis speech in other languages such as English and Chinese using the voices of my Japanese speakers.

Having read the document and issues, it seems that this repository only support CSS10 and Common Voice data set. Also, it seems that English is not supported.

What modifications should I do in order to apply this tool to my custom Japanese data?

Thanks in advance.

**Comment by Tomiinek** [comment]
Hello, you are right. This repo contains only CSS10 and my little Common Voice subset. If you want to add your own data, you need to modify the file with meta-data and provide your audios/spectrograms. Have you seen #7 ? I think you should be ok with taking CSS10 + CV, add your custom data (including japanese CSS10) to it and retrain the model from scratch.

**Comment by zzxiang** [comment]
Thank you. I have read #7 . The result pasted on https://github.com/Tomiinek/Multilingual_Text_to_Speech/issues/7#issuecomment-698951339 is great.

Now I have roughly known how to start my own training. There may be other questions. Please let me submit them in other new issues.

Thanks again.
