### ISSUE TITLE
torch version issue

### ISSUE THREAD

**Issue by XSXIEYCH** [Tomiinek/Multilingual_Text_to_Speech#76]
hello 
Thank you very much for the model, I can run `python3 prepare_css_spectrograms.py just fine`
However 
When I run the following statement, the model is killed
PYTHONIOENCODING=utf-8 python3 train.py --hyper_parameters generated_switching
Maybe my torch version is wrong, I can't get version 1.3.0 installed on my device
my torch version is 1.11.0
` for epoch in range(initial_epoch, hp.epochs):
        train(args.logging_start, epoch, train_data, model, criterion, optimizer)  `
The above code is the part that doesn't work
Could you give me some help, thanks

**Comment by rlellep** [comment]
Yes, I believe the problem is with your torch version.
I was able to find torch 1.3.0 only on Linux.
Try creating a conda environment in Linux with python 3.7 and then installing requirements with
`pip install -r requirements.txt`

**Comment by XSXIEYCH** [comment]
Yes 
I can create python==3.6 and install torch==1.3.0, but not 3.7
I have set the running memory of my virtual machine to 24 GB, but still my program is killed due to memory reasons
If I don't have a discrete graphics card, how much RAM do I need to prepare?
Thanks for your big support

**Comment by rlellep** [comment]
Try to reduce the batch size to reduce memory consumption (it still has to be divisible by the number of voices so if you have 10 voices then the minimal batch size is 10). With the css10 dataset, you should be fine with 40GB RAM, maybe even a bit less.
