### ISSUE TITLE
data

### ISSUE THREAD

**Issue by xynulgm6020** [Tomiinek/Multilingual_Text_to_Speech#78]
i want to now whether the data dowoloaded from yourwebsite is cleaned by your team

**Comment by Tomiinek** [comment]
Yes it was cleaned by me.

**Comment by xynulgm6020** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tomiinek/Multilingual_Text_to_Speech"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月25日(星期六) 凌晨0:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tomiinek/Multilingual_Text_to_Speech] data (Issue #78)





 
Yes it was cleaned by me.
