### ISSUE TITLE
about   µ and variances σ

### ISSUE THREAD

**Issue by xynulgm6020** [Tomiinek/Multilingual_Text_to_Speech#83]
"We computed means µ and variances σ of audio durations of groups corresponding to examples with the same transcript lengths. Then we removed those with durations outside the interval (µ – 3σ, µ + 3σ)."  Here "groups" means some data of the same language or data of the whole dataset  in other words   µ and variances σ of the specific language or of the whole dataset

**Comment by Tomiinek** [comment]
Hello, thank you for the question!

> of groups corresponding to examples with the same transcript lengths

It means that the groups are made of samples that have transcripts with the same length (one group for 4 character, 5 characters, another for 6 characters ... 190 characters); I guess for all languages together (but I do not remember very well :pensive: ).

**Comment by xynulgm6020** [comment]
different language has different text length for the same audio,  so I'm very confused

**Comment by xynulgm6020** [comment]
different language has different text length for the same length of different audios,  so i'm

**Comment by xynulgm6020** [comment]
Did you delete the silence of  the audio
